import {QuizGame} from '@/components/quiz-game';
import {quizCategories,quizQuestions} from '@/content/quiz';
import {absolute,href,jsonLd,metadata as pageMeta} from '@/lib/site';

export const metadata=pageMeta('Snooker Quiz: Test Your Rules, Players and Tournament Knowledge','Play a free snooker quiz with 60 sourced questions about rules, scoring, players, records, tournaments and history. Five questions per round, with an explanation after every answer.','/quiz/');

export default function QuizPage(){
  const schema={'@context':'https://schema.org','@type':'Quiz',name:'The Snooker Calendar knowledge quiz',description:'A free 60-question snooker knowledge quiz covering rules, tournaments, history, players and records.',url:absolute('/quiz/'),educationalLevel:'Beginner to fan',learningResourceType:'Quiz',isAccessibleForFree:true,numberOfQuestions:quizQuestions.length,hasPart:quizCategories.map(item=>({'@type':'Quiz',name:item.title,numberOfQuestions:20}))};
  const crumbs={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:absolute('/')},{'@type':'ListItem',position:2,name:'Snooker quiz',item:absolute('/quiz/')}]};
  return <main id="main" className="quiz-main"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd(schema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd(crumbs)}}/><div className="breadcrumbs"><a href={href('/')}>Home</a> / Snooker quiz</div><header className="quiz-intro"><div><p className="eyebrow">THE SNOOKER KNOWLEDGE CLUB</p><h1>Love snooker.<br/><em>How much do you know?</em></h1><p>Rules, famous players, Crucible history and the tournaments that shape the season. Answer five questions, learn from every explanation and continue with a new set.</p></div><dl><div><dt>{quizQuestions.length}</dt><dd>questions to explore</dd></div><div><dt>5</dt><dd>questions per round</dd></div><div><dt>≈ 2 min</dt><dd>no timer or sign-up</dd></div></dl></header><QuizGame/><section className="quiz-editorial"><div><p className="eyebrow">HOW IT WORKS</p><h2>Learn between frames.</h2></div><div><p>Choose any category and one of four five-question sets. After each answer you will see the correct response, a short explanation and the source used to check it.</p><p>The question bank focuses on durable rules and verified records. Time-sensitive facts are dated and will be reviewed as the season changes.</p><p><a href={href('/stories/')}>Read the snooker guides ↗</a> · <a href={href('/calendar/season/')}>Explore the 2026/27 calendar ↗</a></p></div></section></main>;
}
