export type QuizCategory='rules'|'tournaments'|'players';
export type QuizQuestion={id:string;category:QuizCategory;question:string;options:[string,string,string,string];answer:number;explanation:string;source:{label:string;url:string}};

export const quizCategories:{id:QuizCategory;number:string;kicker:string;title:string;description:string}[]=[
  {id:'rules',number:'01',kicker:'The essentials',title:'Rules and scoring',description:'Ball values, breaks, fouls and the structure of a frame.'},
  {id:'tournaments',number:'02',kicker:'The season',title:'Tournaments and history',description:'Triple Crown stages, famous venues and how the tour fits together.'},
  {id:'players',number:'03',kicker:'The people',title:'Players and records',description:'Champions, nicknames, landmark titles and memorable maximums.'},
];

const rulebook={label:'WPBSA official rules',url:'https://wpbsa.com/wp-content/uploads/Rulebook-Website-Updated-May-2022-2.pdf'};
const history={label:'WPBSA history of snooker',url:'https://wpbsa.com/about-us/history/'};
const wst={label:'World Snooker Tour',url:'https://www.wst.tv/'};
const calendar={label:'World Snooker Tour calendar',url:'https://www.wst.tv/fullcalendarwithseedingcut-offs/'};
const players={label:'World Snooker Tour player profiles',url:'https://www.wst.tv/players/'};
const records={label:'Guinness World Records',url:'https://www.guinnessworldrecords.com/world-records/fastest-maximum-break-in-snooker'};

export const quizQuestions:QuizQuestion[]=[
  {id:'rules-01',category:'rules',question:'How many points is a red ball worth?',options:['1','2','3','4'],answer:0,explanation:'Each red is worth one point. A player normally follows a red with a nominated colour while reds remain.',source:rulebook},
  {id:'rules-02',category:'rules',question:'Which ball has the highest value?',options:['Pink','Blue','Black','Brown'],answer:2,explanation:'The black is worth seven points, the highest value of any ball.',source:rulebook},
  {id:'rules-03',category:'rules',question:'How many reds are on the table at the start of a standard frame?',options:['10','12','15','18'],answer:2,explanation:'A standard frame begins with 15 reds arranged in a triangle.',source:rulebook},
  {id:'rules-04',category:'rules',question:'After the final red and its colour, which colour is played next?',options:['Green','Yellow','Brown','Blue'],answer:1,explanation:'The colours are then played in ascending value: yellow, green, brown, blue, pink and black.',source:rulebook},
  {id:'rules-05',category:'rules',question:'What is the standard maximum break?',options:['140','147','155','167'],answer:1,explanation:'Fifteen red-black combinations make 120, followed by the six colours for 27 more: 147.',source:rulebook},
  {id:'rules-06',category:'rules',question:'What is the usual minimum penalty for a foul?',options:['2 points','3 points','4 points','5 points'],answer:2,explanation:'Most fouls carry at least four points; a higher-value ball involved can increase the penalty.',source:rulebook},
  {id:'rules-07',category:'rules',question:'Which ball is struck with the cue?',options:['Any red','The lowest colour','The cue ball','The ball on'],answer:2,explanation:'The player strikes the white cue ball, which must then make a legal first contact.',source:rulebook},
  {id:'rules-08',category:'rules',question:'What can decide a frame when the scores are tied after all balls are potted?',options:['A coin toss','A respotted black','A replayed frame','Highest break'],answer:1,explanation:'The black is respotted and the next score or foul decides the frame.',source:rulebook},
  {id:'rules-09',category:'rules',question:'How many frames must a player win in a best-of-11 match?',options:['5','6','7','11'],answer:1,explanation:'The first player to six frames has an unbeatable majority in a best-of-11 match.',source:rulebook},
  {id:'rules-10',category:'rules',question:'How many pockets does a full-size snooker table have?',options:['4','6','8','10'],answer:1,explanation:'There is one pocket at each corner and one at the middle of each long cushion.',source:rulebook},
  {id:'rules-11',category:'rules',question:'After the cue ball is potted, where is it normally played from?',options:['The black spot','Anywhere on the table','In hand from the D','The centre spot'],answer:2,explanation:'The incoming player has the cue ball in hand and plays from within the D.',source:rulebook},
  {id:'rules-12',category:'rules',question:'What must the cue ball contact first on a legal stroke?',options:['A cushion','A ball on','The black','Any object ball'],answer:1,explanation:'The first object-ball contact must be with a ball that is on for that stroke.',source:rulebook},
  {id:'rules-13',category:'rules',question:'What does a player’s “break” measure?',options:['Frames won in a row','Points scored in one visit','Time between shots','Lead in the match'],answer:1,explanation:'A break is the total scored during one uninterrupted visit to the table.',source:rulebook},
  {id:'rules-14',category:'rules',question:'What is a century break?',options:['Exactly 100 points','At least 100 points in one visit','100 frames won','A 100-minute frame'],answer:1,explanation:'Any break of 100 points or more is called a century.',source:rulebook},
  {id:'rules-15',category:'rules',question:'In rules language, what is the “ball on”?',options:['The cue ball','The ball the striker may legally hit first','The highest-value colour','The next ball to be respotted'],answer:1,explanation:'The ball on is the legal target for the cue ball’s first contact.',source:rulebook},
  {id:'rules-16',category:'rules',question:'How many points is the pink worth?',options:['4','5','6','7'],answer:2,explanation:'The pink is worth six points and is the second-highest-value colour.',source:rulebook},
  {id:'rules-17',category:'rules',question:'How many points are the six colours worth when cleared once in order?',options:['21','25','27','30'],answer:2,explanation:'Yellow through black total 2 + 3 + 4 + 5 + 6 + 7 = 27.',source:rulebook},
  {id:'rules-18',category:'rules',question:'How many points come from 15 reds each followed by a black?',options:['105','112','120','127'],answer:2,explanation:'Each red-black pair is eight points, so 15 pairs total 120.',source:rulebook},
  {id:'rules-19',category:'rules',question:'What normally happens to a colour potted while reds remain?',options:['It stays off the table','It is respotted','It becomes worth one point','The frame ends'],answer:1,explanation:'Colours are respotted while reds remain; the final colour clearance is different.',source:rulebook},
  {id:'rules-20',category:'rules',question:'What is the difference between a frame and a match?',options:['There is no difference','A match is made up of one or more frames','A frame lasts several matches','Only finals have frames'],answer:1,explanation:'Players win frames to build the total needed to win the match.',source:rulebook},

  {id:'tournaments-01',category:'tournaments',question:'In which country did snooker develop?',options:['England','India','Australia','South Africa'],answer:1,explanation:'Snooker developed among British Army officers stationed in India during the 19th century.',source:history},
  {id:'tournaments-02',category:'tournaments',question:'Who is commonly credited with inventing snooker?',options:['Joe Davis','Neville Chamberlain','John Roberts','Walter Lindrum'],answer:1,explanation:'British Army officer Neville Chamberlain is credited with devising the game in 1875.',source:history},
  {id:'tournaments-03',category:'tournaments',question:'Which city is home to the Crucible Theatre?',options:['London','Manchester','Sheffield','York'],answer:2,explanation:'The Crucible Theatre is in Sheffield and hosts the final stages of the World Championship.',source:wst},
  {id:'tournaments-04',category:'tournaments',question:'Since which year has the Crucible hosted the World Championship?',options:['1969','1977','1982','1990'],answer:1,explanation:'The championship moved to the Crucible in 1977.',source:history},
  {id:'tournaments-05',category:'tournaments',question:'Which three events form snooker’s Triple Crown?',options:['World, UK and Masters','World, Welsh and Masters','UK, British and Scottish','World, Tour and Players'],answer:0,explanation:'The World Championship, UK Championship and Masters make up the Triple Crown.',source:wst},
  {id:'tournaments-06',category:'tournaments',question:'Which Triple Crown event is invitational rather than a ranking event?',options:['World Championship','UK Championship','Masters','All three'],answer:2,explanation:'The Masters is an invitational and does not award world-ranking prize money.',source:wst},
  {id:'tournaments-07',category:'tournaments',question:'Which event is not part of the Home Nations Series?',options:['English Open','Northern Ireland Open','Scottish Open','German Masters'],answer:3,explanation:'The four Home Nations events are the English, Northern Ireland, Scottish and Welsh Opens.',source:wst},
  {id:'tournaments-08',category:'tournaments',question:'Which city hosts the Northern Ireland Open main event in the 2026 calendar?',options:['Belfast','Dublin','Leicester','Glasgow'],answer:0,explanation:'The main event is listed for Belfast; its qualifying stage is held separately in Leicester.',source:calendar},
  {id:'tournaments-09',category:'tournaments',question:'Which venue hosts the UK Championship main event?',options:['Crucible Theatre','York Barbican','Alexandra Palace','Waterfront Hall'],answer:1,explanation:'The final stages of the UK Championship are played at York Barbican.',source:calendar},
  {id:'tournaments-10',category:'tournaments',question:'Which London venue hosts the Masters?',options:['Royal Albert Hall','Alexandra Palace','Wembley Arena','O2 Arena'],answer:1,explanation:'The Masters is staged at Alexandra Palace, widely known as Ally Pally.',source:calendar},
  {id:'tournaments-11',category:'tournaments',question:'Which BBC series helped bring colour snooker to television in 1969?',options:['Frame One','Pot Black','Cue Time','The Green Baize'],answer:1,explanation:'Pot Black launched in 1969 and became an important part of snooker’s television growth.',source:history},
  {id:'tournaments-12',category:'tournaments',question:'How many frames must a player win in the modern World Championship final?',options:['10','13','17','18'],answer:3,explanation:'The final is best of 35 frames, so the champion must reach 18.',source:wst},
  {id:'tournaments-13',category:'tournaments',question:'What is the maximum number of frames in a best-of-35 match?',options:['31','33','35','37'],answer:2,explanation:'“Best of 35” means the match can last up to 35 frames.',source:rulebook},
  {id:'tournaments-14',category:'tournaments',question:'What makes the Snooker Shoot Out format unusual?',options:['No colours are used','Matches are one timed frame','It is doubles only','The table has four pockets'],answer:1,explanation:'Shoot Out matches use one timed frame with additional shot-clock rules.',source:wst},
  {id:'tournaments-15',category:'tournaments',question:'What currently determines the main world ranking list?',options:['A judges’ vote','Career centuries','Eligible prize money over a rolling period','Only the current season’s wins'],answer:2,explanation:'The list is based on eligible ranking prize money over a rolling two-year period.',source:wst},
  {id:'tournaments-16',category:'tournaments',question:'What type of event is Champion of Champions?',options:['Open amateur event','Invitational event','Qualifying school','Women’s ranking event'],answer:1,explanation:'The field is invitation-based and built around qualified tournament winners and other criteria.',source:wst},
  {id:'tournaments-17',category:'tournaments',question:'Does UK Championship prize money count toward the world rankings?',options:['Yes','No','Only for the winner','Only in qualifying'],answer:0,explanation:'The UK Championship is a ranking event, so eligible prize money contributes to the list.',source:wst},
  {id:'tournaments-18',category:'tournaments',question:'Why can a qualifier and main event have separate calendar pages?',options:['They may use different dates and venues','They use different rules','Qualifying has no scores','Only the final is official'],answer:0,explanation:'Qualifying can take place earlier and in another city, so separate records prevent date and venue confusion.',source:calendar},
  {id:'tournaments-19',category:'tournaments',question:'Who won the 2025 Northern Ireland Open?',options:['Judd Trump','Jack Lisowski','Mark Selby','Kyren Wilson'],answer:1,explanation:'Jack Lisowski beat Judd Trump 9–8 to win his first ranking title.',source:{label:'WST: Lisowski’s 2025 title',url:'https://www.wst.tv/news/2025/november/06/lisowski-is-october-player-of-the-month/'}},
  {id:'tournaments-20',category:'tournaments',question:'Who won the 2025 UK Championship?',options:['Mark Selby','John Higgins','Wu Yize','Shaun Murphy'],answer:0,explanation:'Mark Selby captured the 2025 UK Championship title in York.',source:{label:'WST: 2025 UK Championship final',url:'https://www.wst.tv/news/2025/december/07/selby-capture-uk-crown-in-york/'}},

  {id:'players-01',category:'players',question:'Which player is known as “The Rocket”?',options:['Ronnie O’Sullivan','Judd Trump','Neil Robertson','Mark Williams'],answer:0,explanation:'Ronnie O’Sullivan’s speed and attacking talent helped establish “The Rocket” nickname.',source:players},
  {id:'players-02',category:'players',question:'Who is “The Jester from Leicester”?',options:['Mark Selby','Tom Ford','Ben Woollaston','Joe O’Connor'],answer:0,explanation:'Four-time world champion Mark Selby carries the nickname.',source:players},
  {id:'players-03',category:'players',question:'Which player is called “The Wizard of Wishaw”?',options:['Stephen Hendry','John Higgins','Graeme Dott','Stephen Maguire'],answer:1,explanation:'John Higgins is from Wishaw in Scotland and is known as the Wizard of Wishaw.',source:players},
  {id:'players-04',category:'players',question:'Who is known as “The Welsh Potting Machine”?',options:['Ryan Day','Matthew Stevens','Mark Williams','Jak Jones'],answer:2,explanation:'Mark Williams earned the nickname through his exceptional single-ball potting.',source:players},
  {id:'players-05',category:'players',question:'Who is “The Thunder from Down Under”?',options:['Neil Robertson','Eddie Charlton','Quinten Hann','Vinnie Calabrese'],answer:0,explanation:'Australian world champion Neil Robertson uses the nickname.',source:players},
  {id:'players-06',category:'players',question:'Which player is nicknamed “The Ace in the Pack”?',options:['Judd Trump','Mark Allen','Ali Carter','Kyren Wilson'],answer:0,explanation:'Judd Trump is widely known as the Ace in the Pack.',source:players},
  {id:'players-07',category:'players',question:'Who is known as “The Whirlwind”?',options:['Jimmy White','Steve Davis','Cliff Thorburn','Tony Knowles'],answer:0,explanation:'Jimmy White’s fast, attacking style inspired the nickname.',source:players},
  {id:'players-08',category:'players',question:'Who made the first officially recognised televised 147?',options:['Steve Davis','Ronnie O’Sullivan','Cliff Thorburn','Stephen Hendry'],answer:0,explanation:'Steve Davis compiled the first officially recognised televised maximum at the 1982 Lada Classic.',source:history},
  {id:'players-09',category:'players',question:'Who made the first maximum break at the Crucible?',options:['Alex Higgins','Cliff Thorburn','Steve Davis','Dennis Taylor'],answer:1,explanation:'Cliff Thorburn made the first Crucible 147 during the 1983 World Championship.',source:history},
  {id:'players-10',category:'players',question:'Who holds the recognised record for the fastest maximum break?',options:['Ronnie O’Sullivan','Thepchaiya Un-Nooh','Judd Trump','Jimmy White'],answer:0,explanation:'Ronnie O’Sullivan’s 1997 Crucible maximum is recognised at five minutes eight seconds.',source:records},
  {id:'players-11',category:'players',question:'Who became the youngest world champion in 1990?',options:['Ronnie O’Sullivan','Stephen Hendry','John Higgins','Shaun Murphy'],answer:1,explanation:'Stephen Hendry was 21 when he won the 1990 World Championship.',source:history},
  {id:'players-12',category:'players',question:'Who won 15 consecutive World Championship titles?',options:['Joe Davis','Fred Davis','Ray Reardon','Steve Davis'],answer:0,explanation:'Joe Davis won every World Championship staged from 1927 through 1946 before retiring from the event.',source:history},
  {id:'players-13',category:'players',question:'Which qualifier won the 2005 World Championship?',options:['Shaun Murphy','Graeme Dott','Peter Ebdon','Ken Doherty'],answer:0,explanation:'Shaun Murphy came through qualifying and won the title at the Crucible.',source:players},
  {id:'players-14',category:'players',question:'Who became the first Asian player to reach the World Championship final?',options:['Ding Junhui','Marco Fu','James Wattana','Zhao Xintong'],answer:0,explanation:'Ding Junhui reached the 2016 final, where he finished runner-up to Mark Selby.',source:players},
  {id:'players-15',category:'players',question:'Who became the first world champion from mainland Europe in 2023?',options:['Luca Brecel','Tony Drago','Robin Hull','Bjorn Haneveer'],answer:0,explanation:'Belgium’s Luca Brecel won the 2023 title at the Crucible.',source:players},
  {id:'players-16',category:'players',question:'Who became the first Chinese World Snooker Champion?',options:['Ding Junhui','Zhao Xintong','Wu Yize','Yan Bingtao'],answer:1,explanation:'Zhao Xintong became the first Chinese winner of the professional World Championship in 2025.',source:players},
  {id:'players-17',category:'players',question:'Who became the second Chinese World Champion in 2026?',options:['Wu Yize','Si Jiahui','Zhou Yuelong','Lei Peifan'],answer:0,explanation:'Wu Yize defeated Shaun Murphy 18–17 in the 2026 final.',source:{label:'WST: Wu Yize profile',url:'https://www.wst.tv/players/d935d534-e696-4292-b773-e9b8efee1ea7'}},
  {id:'players-18',category:'players',question:'Which player won both the amateur and professional world titles?',options:['Ken Doherty','Dennis Taylor','Mark Allen','Barry Hawkins'],answer:0,explanation:'Ken Doherty won the World Amateur Championship in 1989 and the professional title in 1997.',source:players},
  {id:'players-19',category:'players',question:'At which event did Jack Lisowski win his first ranking title?',options:['2025 Northern Ireland Open','2025 UK Championship','2026 Welsh Open','2025 Scottish Open'],answer:0,explanation:'Lisowski beat Judd Trump 9–8 in Belfast to end his wait for a ranking title.',source:{label:'WST: Jack Lisowski profile',url:'https://www.wst.tv/players/d56f02ab-f2df-41ca-b9a4-24167aded141'}},
  {id:'players-20',category:'players',question:'Which event gave Wu Yize his first ranking title?',options:['2025 International Championship','2026 World Championship','2025 Scottish Open','2026 Masters'],answer:0,explanation:'Wu beat John Higgins 10–6 in the 2025 International Championship final in Nanjing.',source:{label:'WST: Wu Yize profile',url:'https://www.wst.tv/players/d935d534-e696-4292-b773-e9b8efee1ea7'}},
];
