import {notFound} from 'next/navigation';
import {pages} from '@/content/pages';
import {players} from '@/content/players';
import {StoryCards} from '@/components/content-cards';
import {rankings,matchStats,dataSource,dataChecked} from '@/content/data';
import {metadata as pageMeta,href,site} from '@/lib/site';

export function generateStaticParams(){return [...pages.map(p=>({section:p.slug})),{section:'news'},{section:'stories'},{section:'players'},{section:'rankings'},{section:'stats'}]}
export async function generateMetadata({params}:{params:Promise<{section:string}>}){const {section}=await params;const item=pages.find(p=>p.slug===section);const titles={news:'Snooker News & Schedule Briefings',stories:'Snooker Guides, History & Viewing Advice',players:'Snooker Player Database',rankings:'World Snooker Rankings 2026/27',stats:'Snooker Match Statistics 2026/27'} as Record<string,string>;return pageMeta(item?.title||titles[section]||'Page not found',item?.description||'Sourced snooker data, original reading and practical guides from The Snooker Calendar.',`/${section}/`)}
function linkedText(p:string){if(!p.includes(site.email))return p;const [before,after]=p.split(site.email);return <>{before}<a href={`mailto:${site.email}`}>{site.email}</a>{after}</>}

export default async function Page({params}:{params:Promise<{section:string}>}){const {section}=await params;
 if(section==='privacy')return <main id="main" className="article-main"><div className="breadcrumbs"><a href={href('/')}>Home</a> / Privacy policy</div><article><header className="article-header"><p className="eyebrow">THE SNOOKER CALENDAR</p><h1>Privacy policy</h1><p className="lede">How The Snooker Calendar handles analytics, visitor information, calendar downloads and contact email.</p></header><div className="prose"><section><h2>Current scope</h2><p>Effective 10 September 2026. This policy covers The Snooker Calendar at snookercalendar.com.</p><p>For a privacy question or request, email <a href={`mailto:${site.email}`}>{site.email}</a>. Do not send passwords, payment details or identity documents.</p></section><section><h2>Analytics</h2><p>We use Google Analytics 4 to understand aggregate website use, including pages visited, approximate location, device type and referral source. The Google Analytics tag loads when you visit the site. We do not use analytics to identify individual visitors.</p><p>Google may process analytics data under its own terms and privacy policy. You can limit analytics through browser settings, privacy extensions or Google controls where available.</p></section><section><h2>Website visits</h2><p>The site has no user accounts, comments or newsletter forms. Calendar filters run in your browser, and search terms are not sent to an application database.</p><p>Hosting and delivery providers may process IP addresses, browser information and request logs to serve pages, maintain security and diagnose errors.</p></section><section><h2>Email and downloads</h2><p>If you contact {site.email}, we receive your address and the information you choose to include. We use correspondence to respond to the enquiry or investigate a reported issue, not to enrol you in marketing.</p><p>Calendar downloads are static files. Importing a file gives your calendar application event details, not access to your calendar account.</p></section><section><h2>Advertising and external links</h2><p>Links to organisers and other websites take you to services with their own privacy practices. No Google AdSense advertising code is active.</p></section><p>Provider policies: <a href="https://openai.com/policies/privacy-policy/">OpenAI</a> · <a href="https://policies.google.com/privacy">Google</a>.</p></div></article></main>;
 if(section==='news')return <main id="main"><section className="intro"><div><p className="eyebrow">THE SNOOKER DESK</p><h1>News and<br/><em>schedule briefings.</em></h1><p className="lede">Sourced tournament updates and original analysis. Articles carry their source links and check date; this is not a live score service.</p></div></section><StoryCards category="News"/></main>;
 if(section==='stories')return <main id="main"><section className="intro"><div><p className="eyebrow">GUIDES & CULTURE</p><h1>Between<br/><em>the frames.</em></h1><p className="lede">Rules, viewing guides and the history that gives a season its context.</p></div></section><StoryCards category="Guide"/><section className="editorial-section"><div className="section-bar"><h2>History of the game</h2></div><StoryCards category="History"/></section></main>;
 if(section==='players')return <main id="main"><section className="intro"><div><p className="eyebrow">PLAYER DATABASE</p><h1>The people behind<br/><em>the breaks.</em></h1><p className="lede">Editorial profiles with verified career context. Season records and head-to-head pages will be added in stages as their source data is checked.</p></div></section><div className="profile-grid">{players.map(p=><article className="profile-card" key={p.slug}><div className="initials" aria-hidden="true">{p.initials}</div><div><p className="eyebrow">{p.country} · PRO SINCE {p.pro}</p><h2><a href={href(`/players/${p.slug}/`)}>{p.name}</a></h2><p>{p.description}</p><a className="text-link" href={href(`/players/${p.slug}/`)}>Meet {p.name} ↗</a></div></article>)}</div><div className="data-status"><strong>Coverage in progress</strong><p>Player pages are expanding with source-verified season records and head-to-head results. Each page states what has been checked.</p></div><p className="data-source">Structured data source: <a href="https://www.snooker.org/">Snooker.org ↗</a>. Editorial biographies remain original.</p></main>;
 if(section==='rankings')return <main id="main" className="data-main"><section className="intro"><div><p className="eyebrow">2026/27 DATA</p><h1>World snooker<br/><em>rankings.</em></h1><p className="lede">A top-20 snapshot updated after the Wuhan Open. Ranking points can change after every eligible event.</p></div></section><div className="table-wrap"><table><caption>Top 20 world ranking snapshot</caption><thead><tr><th>Rank</th><th>Player</th><th>Represents</th><th>Points</th></tr></thead><tbody>{rankings.map(r=><tr key={r[0]}><td>{r[0]}</td><th scope="row">{r[1]}</th><td>{r[2]}</td><td>{r[3]}</td></tr>)}</tbody></table></div><p className="data-source"><strong>Data source: <a href={`${dataSource}&template=31`}>Snooker.org ↗</a></strong> · Checked {dataChecked}. This is a dated snapshot, not a live ranking service.</p></main>;
 if(section==='stats')return <main id="main" className="data-main"><section className="intro"><div><p className="eyebrow">2026/27 DATA</p><h1>Match and frame<br/><em>statistics.</em></h1><p className="lede">Selected season leaders and notable records. Draws and walkovers can affect how totals compare.</p></div></section><div className="table-wrap"><table><caption>Selected season match statistics</caption><thead><tr><th>Player</th><th>P</th><th>W</th><th>D</th><th>L</th><th>Frames</th><th>FW</th><th>FL</th><th>Frame %</th></tr></thead><tbody>{matchStats.map(r=><tr key={r[0]}><th scope="row">{r[0]}</th>{r.slice(1).map((v,i)=><td key={i}>{v}</td>)}</tr>)}</tbody></table></div><p className="data-source"><strong>Data source: <a href={`${dataSource}&template=5`}>Snooker.org ↗</a></strong> · Checked {dataChecked}. P/W/D/L are matches played, won, drawn and lost; FW/FL are frames won and lost.</p></main>;
 const item=pages.find(p=>p.slug===section);if(!item)notFound();return <main id="main" className="article-main"><div className="breadcrumbs"><a href={href('/')}>Home</a> / {item.title}</div><article><header className="article-header"><p className="eyebrow">THE SNOOKER CALENDAR</p><h1>{item.title}</h1><p className="lede">{item.description}</p></header><div className="prose">{item.sections.map(s=><section key={s.heading}><h2>{s.heading}</h2>{s.paragraphs.map(p=><p key={p}>{linkedText(p)}</p>)}</section>)}{section==='privacy'&&<p>Provider policies: <a href="https://openai.com/policies/privacy-policy/">OpenAI</a> · <a href="https://policies.google.com/privacy">Google</a>.</p>}{section==='about'&&<p><a href={site.github}>View the publisher’s GitHub profile ↗</a></p>}</div></article></main>
}
