import {notFound} from 'next/navigation';
import {pages} from '@/content/pages';
import {players} from '@/content/players';
import {StoryCards} from '@/components/content-cards';
import {metadata as pageMeta,href,site} from '@/lib/site';
export function generateStaticParams(){return [...pages.map(p=>({section:p.slug})),{section:'news'},{section:'stories'},{section:'players'}]}
export async function generateMetadata({params}:{params:Promise<{section:string}>}){const {section}=await params;const item=pages.find(p=>p.slug===section);return pageMeta(item?.title||({news:'Snooker News & Schedule Briefings',stories:'Snooker Stories, History & Viewing Guides',players:'Snooker Player Profiles'}[section]||'Page not found'),item?.description||'Original snooker reading, sourced facts and practical guides from The Snooker Calendar.',`/${section}/`)}
function linkedText(p:string){if(!p.includes(site.email))return p;const parts=p.split(site.email);return <>{parts[0]}<a href={`mailto:${site.email}`}>{site.email}</a>{parts[1]}</>}
export default async function Page({params}:{params:Promise<{section:string}>}){const {section}=await params;
if(section==='news'||section==='stories')return <main id="main"><section className="intro"><div><p className="eyebrow">THE SNOOKER CALENDAR JOURNAL</p><h1>{section==='news'?'The latest from the desk.':'Between the frames.'}</h1><p className="lede">{section==='news'?'Sourced schedule briefings. Checked 5 September 2026; not a live news feed.':'History, practical guides and a closer look at the decisions behind the score.'}</p></div></section>{section==='news'?<StoryCards category="News"/>:<><StoryCards category="Guide"/><StoryCards category="History"/></>}</main>;
if(section==='players')return <main id="main"><section className="intro"><div><p className="eyebrow">PLAYER PROFILES</p><h1>The people behind<br/><em>the breaks.</em></h1><p className="lede">Four introductions to the players, their milestones and what to watch.</p></div></section><div className="profile-grid">{players.map(p=><article className="profile-card" key={p.slug}><div className="initials" aria-hidden="true">{p.initials}</div><div><p className="eyebrow">{p.country} · PRO SINCE {p.pro}</p><h2><a href={href(`/players/${p.slug}/`)}>{p.name}</a></h2><p>{p.description}</p><a className="text-link" href={href(`/players/${p.slug}/`)}>Meet {p.name} ↗</a></div></article>)}</div><p className="calendar-footnote">A curated set of profiles, not a world ranking table. Career milestones are checked against the linked governing-body sources.</p></main>;
const item=pages.find(p=>p.slug===section);if(!item)notFound();return <main id="main" className="article-main"><div className="breadcrumbs"><a href={href('/')}>Home</a> / {item.title}</div><article><header className="article-header"><p className="eyebrow">THE SNOOKER CALENDAR</p><h1>{item.title}</h1><p className="lede">{item.description}</p></header><div className="prose">{item.sections.map(s=><section key={s.heading}><h2>{s.heading}</h2>{s.paragraphs.map(p=><p key={p}>{linkedText(p)}</p>)}</section>)}{section==='privacy'&&<p>Provider policies: <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub</a> · <a href="https://openai.com/policies/privacy-policy/">OpenAI</a> · <a href="https://policies.google.com/privacy">Google</a>.</p>}{section==='about'&&<p><a href={site.github}>View the publisher’s GitHub profile ↗</a></p>}</div></article></main>}
