import {notFound} from 'next/navigation';
import {articles} from '@/content/articles';
import {players} from '@/content/players';
import {events,dateLabel} from '@/content/events';
import {metadata as pageMeta,href,absolute,jsonLd,site} from '@/lib/site';

export function generateStaticParams(){return [...articles.map(a=>({section:a.category==='News'?'news':'stories',slug:a.slug})),...players.map(p=>({section:'players',slug:p.slug})),...events.map(e=>({section:'tournaments',slug:e.slug}))]}
export async function generateMetadata({params}:{params:Promise<{section:string;slug:string}>}){const {section,slug}=await params;const a=articles.find(a=>a.slug===slug&&(a.category==='News'?'news':'stories')===section),p=section==='players'?players.find(p=>p.slug===slug):null,e=section==='tournaments'?events.find(e=>e.slug===slug):null;return pageMeta(a?.title||p?.name||`${e?.name||'Page not found'}: Schedule, Draw & Results`,a?.description||p?.description||`${e?.name}: ${e?dateLabel(e.start,true):''} to ${e?dateLabel(e.end,true):''}. Schedule, draw and results with source attribution.`,`/${section}/${slug}/`)}

export default async function Page({params}:{params:Promise<{section:string;slug:string}>}){const {section,slug}=await params;const a=articles.find(a=>a.slug===slug&&(a.category==='News'?'news':'stories')===section),p=section==='players'?players.find(p=>p.slug===slug):null,e=section==='tournaments'?events.find(e=>e.slug===slug):null;if(!a&&!p&&!e)notFound();const title=a?.title||p?.name||e!.name;const crumbs={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:absolute('/')},{'@type':'ListItem',position:2,name:title,item:absolute(`/${section}/${slug}/`)}]};
 return <main id="main" className="article-main"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd(crumbs)}}/><div className="breadcrumbs"><a href={href('/')}>Home</a> / <a href={href(section==='tournaments'?'/calendar/season/':`/${section}/`)}>{section}</a> / {title}</div><article><header className="article-header"><p className="eyebrow">{a?.category||p?.label||`${e!.tour.toUpperCase()} · ${e!.type.toUpperCase()}`}</p><h1>{title}</h1><p className="lede">{a?.description||p?.description||`${dateLabel(e!.start,true)} – ${dateLabel(e!.end,true)} · ${e!.city}, ${e!.country}`}</p><div className="byline"><a href={href('/about/')}>The Snooker Calendar</a><span>·</span><time dateTime="2026-09-07">Checked 7 September 2026</time></div></header>
 {a&&<><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd({'@context':'https://schema.org','@type':'Article',headline:a.title,description:a.description,datePublished:a.date,dateModified:a.date,inLanguage:'en',mainEntityOfPage:absolute(`/${section}/${slug}/`),author:{'@type':'Organization',name:site.name,url:absolute('/about/')},publisher:{'@type':'Organization',name:site.name,url:absolute('/')},isAccessibleForFree:true})}}/><div className="prose">{a.sections.map(s=><section key={s.heading}><h2>{s.heading}</h2>{s.paragraphs.map(x=><p key={x}>{x}</p>)}</section>)}<aside className="sources"><h2>Sources & editorial note</h2><ul>{a.sources.map(s=><li key={s.url}><a href={s.url}>{s.label} ↗</a></li>)}</ul><p>Original synthesis and commentary, prepared with AI assistance. This article does not claim first-hand reporting or player interviews. <a href={href('/editorial-policy/')}>Read our editorial policy.</a></p></aside></div></>}
 {p&&<><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd({'@context':'https://schema.org','@type':'ProfilePage',mainEntity:{'@type':'Person',name:p.name,jobTitle:'Professional snooker player',sameAs:p.source},dateModified:'2026-09-07'})}}/><div className="prose"><dl className="fact-grid"><div><dt>Represents</dt><dd>{p.country}</dd></div><div><dt>Born</dt><dd>{p.born}</dd></div><div><dt>First turned pro</dt><dd>{p.pro}</dd></div></dl><h2>Career in focus</h2><p>{p.bio}</p><h2>Three milestones</h2><ul>{p.milestones.map(m=><li key={m}>{m}</li>)}</ul><h2>A viewing prompt</h2><p>{p.watch}</p><aside className="sources"><h2>Profile source</h2><a href={p.source}>Official player profile ↗</a><p>Biography and viewing guidance are original editorial work. Structured season results and head-to-head records will appear after the data feed is approved.</p></aside></div></>}
 {e&&<><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd({'@context':'https://schema.org','@type':'SportsEvent',name:e.name,startDate:e.start,endDate:e.end,url:absolute(`/tournaments/${e.slug}/`),description:e.note,sport:'Snooker',location:{'@type':'Place',name:e.venue,address:{'@type':'PostalAddress',addressLocality:e.city,addressCountry:e.country}}})}}/><div className="prose"><dl className="fact-grid"><div><dt>Dates</dt><dd>{dateLabel(e.start)} – {dateLabel(e.end,true)}</dd></div><div><dt>Venue</dt><dd>{e.venue}</dd></div><div><dt>Tour</dt><dd>{e.tour}</dd></div><div><dt>Type</dt><dd>{e.type}</dd></div></dl><nav className="event-tabs" aria-label="Event page sections"><a href="#schedule">Schedule</a><a href="#draw">Draw</a><a href="#results">Results</a></nav><p>{e.note}</p><section id="schedule"><h2>Schedule</h2><p>The event window runs from <strong>{dateLabel(e.start,true)}</strong> to <strong>{dateLabel(e.end,true)}</strong> at {e.venue}, {e.city}. Session-level order of play will be added through the approved data feed. Always check the source before travel.</p></section><section id="draw"><h2>Draw</h2><div className="data-status"><strong>Draw data pending</strong><p>The page structure is ready. The complete draw will appear here after Snooker.org API access is approved, so player pairings are not copied manually or presented as live.</p></div></section><section id="results"><h2>Results</h2>{e.winner?<div className="result-card"><span>Final</span><strong>{e.winner} {e.finalScore} {e.runnerUp}</strong>{e.firstPrize&&<p>Winner’s prize: {e.firstPrize}</p>}</div>:<div className="data-status"><strong>{new Date(e.end+'T23:59:59Z')<new Date('2026-09-07T00:00:00Z')?'Result awaiting verification':'Results will appear after play begins'}</strong><p>Verified scores will be added through the authorized feed. This page does not infer results from an event’s scheduled dates.</p></div>}</section><h2>Save the dates</h2><p><a className="action-link" href={href(`/calendars/${e.slug}.ics`)} download>↓ Download this event (.ics)</a></p><aside className="sources"><h2>Data source</h2><p><strong>Data source: <a href={e.source}>Snooker.org ↗</a></strong></p><p>Checked 7 September 2026. Dates and venues are a dated snapshot. Session times, draws and results may change.</p></aside></div></>}
 <div className="article-end"><a href={href('/calendar/season/')}>← Explore the season calendar</a><a href={`mailto:${site.email}?subject=${encodeURIComponent('Correction: '+title)}`}>Suggest a correction ↗</a></div></article></main>
}
