import type {Metadata} from 'next';
import Script from 'next/script';
import './globals.css';
import './results.css';
import {href,absolute,jsonLd,site} from '@/lib/site';

export const metadata:Metadata={title:'Snooker News, Results & 2026/27 Tournament Calendar',description:'Snooker news, tournament schedules, results, rankings, player profiles and original guides for the 2026/27 season.',icons:{icon:href('/favicon.svg')},alternates:{types:{'application/rss+xml':absolute('/feed.xml')}}};

export default function RootLayout({children}:{children:React.ReactNode}){
 return <html lang="en"><body><Script src="https://www.googletagmanager.com/gtag/js?id=G-4DVDNG8GE0" strategy="afterInteractive"/><Script id="google-analytics" strategy="afterInteractive">{`window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'G-4DVDNG8GE0');`}</Script><a className="skip" href="#main">Skip to content</a><div className="topbar"><span>INDEPENDENT SNOOKER. ALL SEASON.</span><span>2026 / 27 EDITION</span></div><header className="masthead"><a href={href('/')} className="brand">THE SNOOKER<span>CALENDAR<span className="brand-dot">.</span></span></a><nav aria-label="Main navigation"><a href={href('/news/')}>News</a><a href={href('/calendar/season/')}>Schedule & results</a><a href={href('/rankings/')}>Rankings</a><a href={href('/players/')}>Players</a><a href={href('/stories/')}>Guides</a></nav><span className="season-label">THE SEASON, IN FRAME ↗</span></header><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd({'@context':'https://schema.org','@type':'WebSite',name:site.name,url:absolute('/'),inLanguage:'en'})}}/>{children}<footer><div className="footer-top"><a href={href('/')} className="brand">THE SNOOKER<span>CALENDAR.</span></a><p>An independent guide to the game.<br/>The tournaments. The players. The stories between frames.</p></div><div className="footer-bottom"><span>© 2026 The Snooker Calendar</span><nav aria-label="Footer"><a href={href('/news/')}>News</a><a href={href('/calendar/season/')}>Schedule</a><a href={href('/stories/')}>Guides</a><a href={href('/about/')}>About</a><a href={href('/editorial-policy/')}>Editorial policy</a><a href={href('/contact/')}>Contact</a><a href={href('/privacy/')}>Privacy</a><a href={href('/terms/')}>Terms</a><a href={href('/feed.xml')}>RSS</a></nav><span>Not affiliated with WST or WPBSA.</span></div></footer></body></html>
}
