import {readFileSync,readdirSync,existsSync,statSync} from 'node:fs';
import {join} from 'node:path';
import assert from 'node:assert/strict';
import {events,months,inMonth} from '../content/events.ts';
import {articles} from '../content/articles.ts';
import {players} from '../content/players.ts';
import {rankings} from '../content/data.ts';
const origin=(process.env.NEXT_PUBLIC_SITE_URL||'https://snookercalendar.com').replace(/\/$/,'');
const base=process.env.NEXT_PUBLIC_BASE_PATH||'';
const files=[];const walk=d=>{for(const e of readdirSync(d,{withFileTypes:true})){const p=join(d,e.name);if(e.isDirectory())walk(p);else if(p.endsWith('.html'))files.push(p)}};walk('out');
const errors=[],titles=new Set(),canonicals=new Set();
for(const file of files){const html=readFileSync(file,'utf8');if(file.endsWith('404.html'))continue;const title=html.match(/<title>([\s\S]*?)<\/title>/)?.[1];if(!title||titles.has(title))errors.push(file+': missing/duplicate title');titles.add(title);if(!/<meta\b[^>]*name="description"[^>]*content="[^"]+"/.test(html))errors.push(file+': missing description');const c=html.match(/<link\b[^>]*rel="canonical"[^>]*href="([^"]+)"/)?.[1];if(!c||!c.startsWith(origin+'/')||canonicals.has(c))errors.push(file+': bad canonical '+c);canonicals.add(c);if((html.match(/<h1(?:\s|>)/g)||[]).length!==1)errors.push(file+': must have one H1');for(const m of html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)){try{JSON.parse(m[1])}catch{errors.push(file+': invalid JSON-LD')}}for(const m of html.matchAll(/(?:href|src)="(\/[^"#?]*)/g)){let path=decodeURIComponent(m[1]);if(base){if(!path.startsWith(base+'/')){errors.push(file+': missing base path '+path);continue}path=path.slice(base.length)}const target=join('out',path);if(!(existsSync(target)&&(statSync(target).isFile()||existsSync(join(target,'index.html')))))errors.push(file+': missing local resource '+path)}}
const expectedPages=2+months.length+10+articles.length+players.length+events.length;const sitemap=readFileSync('out/sitemap.xml','utf8');assert.equal((sitemap.match(/<loc>/g)||[]).length,expectedPages);assert.equal(canonicals.size,expectedPages);assert.equal(events.length,58);assert.equal(events.length,new Set(events.map(e=>e.slug)).size);assert.equal(players.length,50);assert.equal(rankings.length,50);assert.equal(players.length,new Set(players.map(p=>p.slug)).size);for(const e of events)assert.ok(e.start<=e.end);assert.ok(inMonth(events.find(e=>e.slug==='british-open-2026'),'2026-09'));const ics=readFileSync('out/calendars/season.ics','utf8');assert.equal((ics.match(/BEGIN:VEVENT/g)||[]).length,events.length);assert.ok(ics.includes('DTEND;VALUE=DATE:20260907'));for(const line of ics.split('\r\n'))assert.ok(Buffer.byteLength(line)<=75);const liveScore=JSON.parse(readFileSync('out/data/live-score.json','utf8'));assert.equal(liveScore.eventSlug,'english-open-2026');assert.ok(liveScore.verifiedResults.length>0);const rankingData=JSON.parse(readFileSync('out/data/rankings.json','utf8'));assert.equal(rankingData.official.positions.length,50);assert.ok(!readFileSync('out/index.html','utf8').includes('adsbygoogle'));if(errors.length){console.error(errors.join('\n'));process.exit(1)}console.log(`PASS: ${canonicals.size} content pages; 50 rankings, 50 player profiles, titles, descriptions, canonical URLs, local links/assets, JSON-LD, live data, sitemap and ${events.length} calendar records.`);
